version: 1
projects:
  uri-runner:
    cwd: /home/aleksim/uri-runner-next
    outbox_dir: /home/aleksim/workspace/projects/uri-runner/Outbox
  uri-runner-next:
    cwd: /home/aleksim/uri-runner-next
    outbox_dir: /home/aleksim/workspace/projects/uri-runner/Outbox
  tempasi:
    cwd: /home/aleksim/tempasi
    outbox_dir: /home/aleksim/workspace/projects/tempasi/Outbox
