"use strict";

const ERROR_CODES = Object.freeze({
  COMMAND_NOT_FOUND: "COMMAND_NOT_FOUND",
  COMMAND_NOT_ALLOWED: "COMMAND_NOT_ALLOWED",
  COMMAND_ROOT_NOT_ALLOWED: "COMMAND_ROOT_NOT_ALLOWED",
  ENGINE_NOT_ALLOWED: "ENGINE_NOT_ALLOWED",
  EXECUTION_LOCKED: "EXECUTION_LOCKED",
  MAX_STEPS_EXCEEDED: "MAX_STEPS_EXCEEDED",
  SCENARIO_INVALID: "SCENARIO_INVALID",
  PIPELINE_INTERNAL_ERROR: "PIPELINE_INTERNAL_ERROR",
});

function isKnownErrorCode(code) {
  return Object.prototype.hasOwnProperty.call(ERROR_CODES, code);
}

module.exports = {
  ERROR_CODES,
  isKnownErrorCode,
};
